# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: akdasa
          template: classic
          base: ''
          config_timezone: Asia/Calcutta
          
          # 🗳️ Leetcode
          plugin_leetcode: yes
          plugin_leetcode_user : akdasa
          plugin_leetcode_sections: solved, skills, recent
          
          # ⏰ WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, projects, projects-graphs, editors, os, os-graphs, editors-graphs
          plugin_wakatime_days: 365
